import {
  ContactButton,
  InfoBullet,
  InfoParagraph,
  InfoScreen,
  InfoSection,
  SUPPORT_EMAIL,
} from '@/src/components/profile/InfoScreen';
import { APP_NAME } from '@/src/constants/app';
import { FREE_TIER_LIMITS, PREMIUM_TRIAL_DAYS } from '@/src/constants/subscription';

export default function TermsScreen() {
  return (
    <InfoScreen
      title="Terms of Service"
      subtitle={`Please read these terms carefully. By using ${APP_NAME}, you agree to them.`}
      lastUpdated="May 2026"
    >
      <InfoSection title="Acceptance of terms">
        <InfoParagraph>
          By creating an account or using {APP_NAME}, you agree to these Terms of Service and our
          Privacy Policy. If you do not agree, please discontinue use of the app.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title={`What ${APP_NAME} provides`}>
        <InfoParagraph>
          {APP_NAME} offers Scripture-centered encouragement for everyday life, including:
        </InfoParagraph>
        <InfoBullet>AI-assisted guidance chat with verses, reflection, and prayer.</InfoBullet>
        <InfoBullet>Daily encouragement (verse, prayer, and reflection prompt).</InfoBullet>
        <InfoBullet>A private journal and saved reflections, including weekly folders.</InfoBullet>
        <InfoBullet>Multi-day devotional plans (Premium).</InfoBullet>
        <InfoParagraph>
          A free tier is available with limits (such as {FREE_TIER_LIMITS.dailyChatLimit} guidance
          chats per day, browsing journal entries from the last{' '}
          {FREE_TIER_LIMITS.journalHistoryDays} days, up to{' '}
          {FREE_TIER_LIMITS.savedReflectionsLimit} saved verses/prayers/guidance items, and the Sage
          Mist color theme only). Premium unlocks additional features and may include a{' '}
          {PREMIUM_TRIAL_DAYS}-day introductory trial, then a recurring subscription billed through
          Apple or Google.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Not professional advice">
        <InfoParagraph>
          The guidance in this app is for spiritual encouragement only. It is not a substitute for
          professional medical, mental-health, legal, or financial advice, nor for pastoral care from
          your local church or a qualified counselor.
        </InfoParagraph>
        <InfoParagraph>
          If you are experiencing a crisis or thoughts of harming yourself or others, please contact
          your local emergency services or a crisis hotline immediately. The app includes a crisis
          support screen for quick reference.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Subscriptions">
        <InfoBullet>
          Premium subscriptions must be purchased through Apple In-App Purchase or Google Play Billing
          inside the app. We do not offer web checkout or alternative payment methods for digital
          subscriptions.
        </InfoBullet>
        <InfoBullet>
          Trial and billing terms are shown on the paywall before purchase. Subscriptions renew
          automatically unless cancelled in your device subscription settings.
        </InfoBullet>
        <InfoBullet>Restore Purchases is available for eligible prior purchases on the same store account.</InfoBullet>
      </InfoSection>

      <InfoSection title="Your account">
        <InfoBullet>You are responsible for keeping your login credentials secure.</InfoBullet>
        <InfoBullet>You agree to provide accurate information when registering.</InfoBullet>
        <InfoBullet>You are responsible for activity that occurs under your account.</InfoBullet>
        <InfoBullet>You may delete your account from Settings; this removes synced cloud data we control.</InfoBullet>
      </InfoSection>

      <InfoSection title="Acceptable use">
        <InfoParagraph>You agree not to:</InfoParagraph>
        <InfoBullet>Use the app for any unlawful or harmful purpose.</InfoBullet>
        <InfoBullet>Attempt to disrupt, reverse-engineer, or abuse the service.</InfoBullet>
        <InfoBullet>
          Misrepresent AI-generated content as professional, medical, or authoritative counsel.
        </InfoBullet>
        <InfoBullet>Circumvent subscription or usage limits (including automated or excessive requests).</InfoBullet>
      </InfoSection>

      <InfoSection title="AI-generated content">
        <InfoParagraph>
          Responses are generated by artificial intelligence and may occasionally be inaccurate,
          incomplete, or not reflect your own tradition&apos;s interpretation of Scripture. The app
          may decline off-topic requests outside faith-centered reflection. Always weigh guidance
          prayerfully and consult trusted spiritual leaders and the Bible itself.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Scripture & intellectual property">
        <InfoParagraph>
          Bible translations included in the app remain the property of their respective copyright
          holders and are provided for personal, devotional use. The {APP_NAME} name, design, logo, and
          original content are owned by us and may not be copied without permission.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Limitation of liability">
        <InfoParagraph>
          To the fullest extent permitted by law, {APP_NAME} and its creators are not liable for any
          decisions you make based on content in the app, or for any indirect or incidental damages
          arising from its use. The app is provided &quot;as is&quot; without warranties of any kind.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Termination">
        <InfoParagraph>
          You may stop using the app and delete your account at any time. We may suspend or terminate
          access if these terms are violated.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Changes to these terms">
        <InfoParagraph>
          We may update these terms from time to time. Continued use of the app after changes take
          effect means you accept the revised terms.
        </InfoParagraph>
      </InfoSection>

      <InfoSection title="Contact us">
        <InfoParagraph>Questions about these terms? Reach us at {SUPPORT_EMAIL}.</InfoParagraph>
        <ContactButton />
      </InfoSection>
    </InfoScreen>
  );
}
