export const BOOK_ID: Record<string, string> = {
  Genesis: 'GEN',
  Exodus: 'EXO',
  Leviticus: 'LEV',
  Numbers: 'NUM',
  Deuteronomy: 'DEU',
  Joshua: 'JOS',
  Judges: 'JDG',
  Ruth: 'RUT',
  '1st Samuel': '1SA',
  '2nd Samuel': '2SA',
  '1st Kings': '1KI',
  '2nd Kings': '2KI',
  '1st Chronicles': '1CH',
  '2nd Chronicles': '2CH',
  Ezra: 'EZR',
  Nehemiah: 'NEH',
  Esther: 'EST',
  Job: 'JOB',
  Psalms: 'PSA',
  Proverbs: 'PRO',
  Ecclesiastes: 'ECC',
  'Song of Solomon': 'SNG',
  Isaiah: 'ISA',
  Jeremiah: 'JER',
  Lamentations: 'LAM',
  Ezekiel: 'EZK',
  Daniel: 'DAN',
  Hosea: 'HOS',
  Joel: 'JOL',
  Amos: 'AMO',
  Obadiah: 'OBA',
  Jonah: 'JON',
  Micah: 'MIC',
  Nahum: 'NAM',
  Habakkuk: 'HAB',
  Zephaniah: 'ZEP',
  Haggai: 'HAG',
  Zechariah: 'ZEC',
  Malachi: 'MAL',
  Matthew: 'MAT',
  Mark: 'MRK',
  Luke: 'LUK',
  John: 'JHN',
  Acts: 'ACT',
  Romans: 'ROM',
  '1st Corinthians': '1CO',
  '2nd Corinthians': '2CO',
  Galatians: 'GAL',
  Ephesians: 'EPH',
  Philippians: 'PHP',
  Colossians: 'COL',
  '1st Thessalonians': '1TH',
  '2nd Thessalonians': '2TH',
  '1st Timothy': '1TI',
  '2nd Timothy': '2TI',
  Titus: 'TIT',
  Philemon: 'PHM',
  Hebrews: 'HEB',
  James: 'JAS',
  '1st Peter': '1PE',
  '2nd Peter': '2PE',
  '1st John': '1JN',
  '2nd John': '2JN',
  '3rd John': '3JN',
  Jude: 'JUD',
  Revelation: 'REV',
};

export const ID_TO_BOOK: Record<string, string> = Object.fromEntries(
  Object.entries(BOOK_ID).map(([name, id]) => [id, name]),
);
